# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CADemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CADemo

end

target 'CoreAnimationForMac' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CoreAnimationForMac

end

target 'RouterDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RouterDemo

  target 'RouterDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'UICollectionViewDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UICollectionViewDemo

end

target 'XCARMAssembly' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XCARMAssembly

end

target 'XCAutoLayoutDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XCAutoLayoutDemo

end

target 'XCDrawing' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XCDrawing

end

target 'XCTestApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XCTestApp

end
